apiVersion: v1
kind: Service
metadata:
    name: "aksdevjpeastsandbox-f915"
    labels:
        app: "aksdevjpeastsandbox-f915"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdevjpeastsandbox-f915"